### ISSUE TITLE
Just letting you know you might have meant to put a different description here

### ISSUE THREAD

**Issue by TFWol** [washingtonalto/bookmarklets#1]
See title.

https://github.com/washingtonalto/bookmarklets/blob/bbfe3e95329b71546ad62e2c55edbaab97f9f392/README.md?plain=1#L37

**Comment by washingtonalto** [comment]
Apologies for the late reply @TFWol  and thank you very much for the  feedback. I rarely update this and I only notice your raising the issue now. I've corrected the README.md for that part.

**Comment by TFWol** [comment]
No problem. I tend to send off a Pull request or Issue if I see something of interest and then keep browsing around GitHub looking at neat stuff.
